# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('FundingOrgId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('FundingOrgName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('LeadROId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('LeadROName', models.CharField(max_length=255)),
                ('Region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('ProjectCategory', models.CharField(max_length=50)),
                ('Department', models.CharField(blank=True, max_length=255, null=True)),
                ('Title', models.CharField(blank=True, max_length=255, null=True)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('FundingAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Status', models.CharField(max_length=6)),
                ('Topic', models.CharField(blank=True, max_length=255, null=True)),
                ('Sectors', models.CharField(blank=True, max_length=255, null=True)),
                ('OECD', models.CharField(blank=True, max_length=4, null=True)),
                ('NABS', models.CharField(blank=True, max_length=5, null=True)),
                ('Funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InnovationMaps.Funder')),
                ('Organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InnovationMaps.Organisation')),
            ],
        ),
    ]
